In [4]:
import numpy as np

### 归一化前

In [5]:
X = np.array([
    [50, 2, 10, 1],   # 面积50平米，2个房间，10年房龄
    [80, 3, 8, 1],    # 面积80平米，3个房间，8年房龄
    [100, 3, 15, 1],  # 面积100平米，3个房间，15年房龄
    [120, 4, 15, 1],  # 面积120平米，4个房间，15年房龄
    [150, 4, 20, 1],  # 面积150平米，4个房间，20年房龄
    [90, 3, 12, 1],   # 面积90平米，3个房间，12年房龄
    [110, 4, 7, 1],   # 面积110平米，4个房间，7年房龄
    [130, 5, 3, 1]    # 面积130平米，5个房间，3年房龄
])
# 对应的房价（单位：万元）
y = np.array([180, 240, 260, 300, 350, 280, 320, 360]) 

${\mathbf{\bar w} = \mathbf{w} - \alpha \nabla f(\mathbf{w})}$ </br> </br>
$\nabla f(\mathbf{w}) = X^TX \mathbf{w} - X^T \mathbf{y}$ 

In [6]:
alpha = 0.1
w = [0, 0, 0, 0]
for i in range(1000):
    w = w - alpha * (X.T @ X @ w - X.T @ y)
w

C:\Users\BeatsLeo\AppData\Local\Temp\ipykernel_27236\4004418720.py:4: RuntimeWarning: overflow encountered in matmul
  w = w - alpha * (X.T @ X @ w - X.T @ y) / 8
C:\Users\BeatsLeo\AppData\Local\Temp\ipykernel_27236\4004418720.py:4: RuntimeWarning: invalid value encountered in subtract
  w = w - alpha * (X.T @ X @ w - X.T @ y) / 8


array([nan, nan, nan, nan])

### 归一化后

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
# 创建StandardScaler
scaler_X = StandardScaler()
scaler_y = StandardScaler()
X_normalized = scaler_X.fit_transform(X)
y_normalized = scaler_y.fit_transform(y.reshape(-1, 1)).reshape(-1)
X_normalized, y_normalized

(array([[-1.84530662, -1.73205081, -0.2478408 ,  0.        ],
        [-0.81536804, -0.57735027, -0.64438608,  0.        ],
        [-0.12874232, -0.57735027,  0.7435224 ,  0.        ],
        [ 0.5578834 ,  0.57735027,  0.7435224 ,  0.        ],
        [ 1.58782198,  0.57735027,  1.73488559,  0.        ],
        [-0.47205518, -0.57735027,  0.14870448,  0.        ],
        [ 0.21457054,  0.57735027, -0.84265872,  0.        ],
        [ 0.90119626,  1.73205081, -1.63574927,  0.        ]]),
 array([-1.90113312, -0.82755207, -0.46969171,  0.24602899,  1.14067987,
        -0.11183136,  0.60388935,  1.31961005]))

In [9]:
alpha = 0.1
w = [0, 0, 0, 0]
for i in range(1000):
    w = w - alpha * (X_normalized.T @ X_normalized @ w - X_normalized.T @ y_normalized)
w

array([ 1.2566944 , -0.22622516, -0.39491766,  0.        ])

### 预测

In [10]:
from sklearn.metrics import mean_squared_error

In [11]:
# 测试数据
X_test = np.array([
    [100, 3, 10, 1],
    [140, 4, 5, 1]
])

# 测试数据的房价
y_test = np.array([290, 395])

# 预测房价
predictions = scaler_X.transform(X_test) @ w
y_pred = scaler_y.inverse_transform(predictions.reshape(-1, 1)).reshape(-1)
print("预测的房价：", y_pred)

mse = mean_squared_error(y_test, y_pred)
print(f"均方误差: {mse}")

预测的房价： [289.97760524 393.70756026]
均方误差: 0.835451004217338


In [12]:
w

array([ 1.2566944 , -0.22622516, -0.39491766,  0.        ])