In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
# 加载数据集
data = load_iris()
X = data.data[::15]
y = data.target[::15]

print('划分前(X):\n', X)
print('划分前(y):\n', y)

划分前(X):
 [[5.1 3.5 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]]
划分前(y):
 [0 0 0 0 1 1 1 2 2 2]


In [4]:
# 将数据集划分为训练集和测试集，这里训练集:测试集为7:3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print('划分后(X_train):\n', X_train)
print('划分后(y_train):\n', y_train)
print('\n')
print('划分后(X_test):\n', X_test)
print('划分后(y_test):\n', y_test)

划分后(X_train):
 [[6.6 3.  4.4 1.4]
 [4.8 3.1 1.6 0.2]
 [5.7 4.4 1.5 0.4]
 [5.  2.  3.5 1. ]
 [7.6 3.  6.6 2.1]
 [7.7 3.  6.1 2.3]
 [5.1 3.5 1.4 0.2]]
划分后(y_train):
 [1 0 0 1 2 2 0]


划分后(X_test):
 [[6.9 3.2 5.7 2.3]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]]
划分后(y_test):
 [2 1 0]
