### 最大-最小归一化（Min-Max Scaling）

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
# 示例数据
data = np.array([[2, 8], [4, 10], [6, 12], [8, 14]])

print("Min-Max归一化前的数据：\n", data)

# 创建MinMaxScaler，将数据缩放到[0, 1]范围内
scaler = MinMaxScaler()
data_normalized = scaler.fit_transform(data)

print("Min-Max归一化后的数据：\n", data_normalized)


Min-Max归一化前的数据：
 [[ 2  8]
 [ 4 10]
 [ 6 12]
 [ 8 14]]
Min-Max归一化后的数据：
 [[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


### 标准化（Z-score Normalization）

In [6]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [8]:
# 示例数据
data = np.array([[2, 8], [4, 10], [6, 12], [8, 14]])

print("标准化前的数据：\n", data)

# 创建StandardScaler
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

print("标准化后的数据：\n", data_standardized)

标准化前的数据：
 [[ 2  8]
 [ 4 10]
 [ 6 12]
 [ 8 14]]
标准化后的数据：
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
